services:
  app:
    container_name: pretix_app
    build:
      dockerfile: Dockerfile
      context: ./docker/pretix
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - pretix_data:/data
      - ./docker/pretix/pretix.cfg:/etc/pretix/pretix.cfg
      - ./docker/pretix/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./docker/pretix/crontab:/tmp/crontab
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - backend

  database:
    image: postgres:16-alpine3.20
    container_name: database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:alpine3.20
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  pretix_data:
    driver: local

networks:
  backend:
    external: false
